export const kpiData = [
  {
    id: 'revenue',
    label: 'إيرادات اليوم',
    value: '18,340',
    unit: 'ر.س',
    delta: '+12%',
    deltaType: 'up',
    note: 'مقارنة بالأمس',
    icon: 'revenue',
  },
  {
    id: 'appointments',
    label: 'المواعيد',
    value: '148',
    unit: '',
    delta: '+8%',
    deltaType: 'up',
    note: 'حجوزات اليوم',
    icon: 'calendar',
  },
  {
    id: 'patients',
    label: 'المرضى الإجمالي',
    value: '3,241',
    unit: '',
    delta: '+4.2%',
    deltaType: 'up',
    note: 'مسجّل هذا الشهر',
    icon: 'patients',
  },
  {
    id: 'occupancy',
    label: 'نسبة الإشغال',
    value: '78',
    unit: '%',
    delta: '-3%',
    deltaType: 'dn',
    note: 'أقل من المستهدف الأسبوعي',
    icon: 'occupancy',
  },
]

export const revenueChartData = [
  { label: 'الأحد',   day: 'أحد',    value: 180000 },
  { label: 'الاثنين', day: 'اثنين',  value: 210000 },
  { label: 'الثلاثاء',day: 'ثلاثاء', value: 195000 },
  { label: 'الأربعاء',day: 'أربعاء', value: 240000 },
  { label: 'الخميس', day: 'خميس',   value: 265000 },
  { label: 'الجمعة', day: 'جمعة',   value: 285000 },
  { label: 'السبت',  day: 'سبت',    value: 320000, highlight: true },
]

export const kpiDataByPeriod = {
  اليوم: kpiData,
  الأسبوع: [
    { ...kpiData[0], value: '126,480', delta: '+9.4%', note: 'مقارنة بالأسبوع السابق' },
    { ...kpiData[1], value: '1,042', delta: '+6.8%', note: 'حجوزات هذا الأسبوع' },
    { ...kpiData[2], value: '3,488', delta: '+5.1%', note: 'إجمالي المرضى النشطين' },
    { ...kpiData[3], value: '82', delta: '+2%', deltaType: 'up', note: 'متوسط الإشغال الأسبوعي' },
  ],
  الشهر: [
    { ...kpiData[0], value: '528,920', delta: '+14.2%', note: 'مقارنة بالشهر السابق' },
    { ...kpiData[1], value: '4,386', delta: '+10.5%', note: 'حجوزات هذا الشهر' },
    { ...kpiData[2], value: '4,126', delta: '+7.6%', note: 'مرضى مسجلون هذا الشهر' },
    { ...kpiData[3], value: '85', delta: '+4%', deltaType: 'up', note: 'متوسط الإشغال الشهري' },
  ],
  السنة: [
    { ...kpiData[0], value: '6,184,300', delta: '+18.6%', note: 'مقارنة بالسنة الماضية' },
    { ...kpiData[1], value: '51,248', delta: '+12.3%', note: 'حجوزات هذه السنة' },
    { ...kpiData[2], value: '18,742', delta: '+16.4%', note: 'إجمالي المرضى المسجلين' },
    { ...kpiData[3], value: '88', delta: '+5%', deltaType: 'up', note: 'متوسط الإشغال السنوي' },
  ],
}

export const revenueChartSeries = {
  أسبوعي: revenueChartData,
  شهري: [
    { day: 'الأسبوع 1', value: 820000 }, { day: 'الأسبوع 2', value: 910000 },
    { day: 'الأسبوع 3', value: 865000 }, { day: 'الأسبوع 4', value: 1030000, highlight: true },
  ],
  سنوي: [
    { day: 'يناير', value: 2450000 }, { day: 'فبراير', value: 2710000 },
    { day: 'مارس', value: 2580000 }, { day: 'أبريل', value: 3020000 },
    { day: 'مايو', value: 3290000 }, { day: 'يونيو', value: 3560000, highlight: true },
  ],
}

export const branchPerformance = [
  { name: 'الرياض',   value: '145k', pct: 100 },
  { name: 'جدة',     value: '118k', pct: 82 },
  { name: 'الدمام',  value: '98k',  pct: 68 },
]

export const recentAppointments = [
  {
    id: 1,
    patientInitial: 'س',
    patientName: 'سارة المطيري',
    patientRef: 'رقم #30412',
    doctorName: 'د. خالد المطيري',
    specialty: 'باطنية',
    branch: 'الرياض',
    time: '15 يوليو · 10:30',
    status: 'ok',
    statusLabel: 'مؤكد',
  },
  {
    id: 2,
    patientInitial: 'م',
    patientName: 'محمد السبيعي',
    patientRef: 'رقم #30298',
    doctorName: 'د. نورة الشمري',
    specialty: 'أطفال',
    branch: 'الرياض',
    time: '15 يوليو · 11:00',
    status: 'warn',
    statusLabel: 'في الانتظار',
  },
  {
    id: 3,
    patientInitial: 'ف',
    patientName: 'فيصل العتيبي',
    patientRef: 'رقم #30115',
    doctorName: 'د. منصور العبيدي',
    specialty: 'عظام',
    branch: 'الرياض',
    time: '15 يوليو · 12:15',
    status: 'ok',
    statusLabel: 'مؤكد',
  },
  {
    id: 4,
    patientInitial: 'ن',
    patientName: 'نور المحيميد',
    patientRef: 'رقم #29882',
    doctorName: 'د. نورة الشمري',
    specialty: 'أطفال',
    branch: 'الرياض',
    time: '15 يوليو · 1:30 م',
    status: 'info',
    statusLabel: 'وصل',
  },
  {
    id: 5,
    patientInitial: 'ع',
    patientName: 'عبدالله الدوسري',
    patientRef: 'رقم #29750',
    doctorName: 'د. خالد المطيري',
    specialty: 'باطنية',
    branch: 'جدة',
    time: '15 يوليو · 2:00 م',
    status: 'danger',
    statusLabel: 'ملغي',
  },
  {
    id: 6,
    patientInitial: 'ه',
    patientName: 'هدى الزهراني',
    patientRef: 'رقم #29640',
    doctorName: 'د. منصور العبيدي',
    specialty: 'عظام',
    branch: 'الدمام',
    time: '15 يوليو · 3:00 م',
    status: 'ok',
    statusLabel: 'مؤكد',
  },
]

export const topDoctors = [
  {
    id: 1,
    initial: 'خ',
    name: 'د. خالد المطيري',
    specialty: 'باطنية',
    patients: 42,
    rating: 4.9,
    revenue: '8.2k',
  },
  {
    id: 2,
    initial: 'ن',
    name: 'د. نورة الشمري',
    specialty: 'أطفال',
    patients: 38,
    rating: 4.8,
    revenue: '7.1k',
  },
  {
    id: 3,
    initial: 'م',
    name: 'د. منصور العبيدي',
    specialty: 'عظام',
    patients: 34,
    rating: 4.7,
    revenue: '6.4k',
  },
  {
    id: 4,
    initial: 'ل',
    name: 'د. لمياء القحطاني',
    specialty: 'جلدية',
    patients: 29,
    rating: 4.9,
    revenue: '5.8k',
  },
]
