export const serviceStats = [
  {
    id: "total",
    label: "إجمالي الخدمات",
    value: "142",
    note: "128 نشطة · 14 متوقفة",
    icon: "bag",
  },
  {
    id: "specialties",
    label: "التخصصات",
    value: "8",
    note: "تخصص طبي",
    icon: "grid",
  },
  {
    id: "top",
    label: "أعلى إيراداً",
    valueText: "كشف عام",
    note: "1,240 مرة/شهر",
    icon: "trend",
  },
  {
    id: "avg",
    label: "متوسط سعر الكشف",
    value: "185",
    unit: "ر.س",
    note: "عبر كل التخصصات",
    icon: "card",
  },
];

export const specialtyFilters = [
  { id: "all", label: "كل التخصصات" },
  { id: "internal", label: "باطنة" },
  { id: "skin", label: "جلدية" },
  { id: "dental", label: "أسنان" },
  { id: "pediatric", label: "أطفال" },
  { id: "gynecology", label: "نساء وولادة" },
  { id: "more", label: "+3" },
];

// status: 'active' | 'inactive'
// specialtyId maps to specialtyFilters ids
export const services = [
  {
    id: 1,
    code: "SVC-001",
    name: "كشف باطنة عام",
    nameEn: "General Internal Medicine",
    specialty: "باطنة",
    specialtyId: "internal",
    priceCash: 150,
    priceInsurance: 200,
    doctors: 6,
    status: "active",
  },
  {
    id: 2,
    code: "SVC-002",
    name: "كشف جلدية",
    nameEn: "Dermatology Consultation",
    specialty: "جلدية",
    specialtyId: "skin",
    priceCash: 180,
    priceInsurance: 220,
    doctors: 4,
    status: "active",
  },
  {
    id: 3,
    code: "SVC-003",
    name: "كشف أسنان أول",
    nameEn: "Dental First Visit",
    specialty: "أسنان",
    specialtyId: "dental",
    priceCash: 100,
    priceInsurance: 150,
    doctors: 5,
    status: "active",
  },
  {
    id: 4,
    code: "SVC-004",
    name: "كشف أطفال",
    nameEn: "Pediatric Consultation",
    specialty: "أطفال",
    specialtyId: "pediatric",
    priceCash: 130,
    priceInsurance: 180,
    doctors: 3,
    status: "active",
  },
  {
    id: 5,
    code: "SVC-101",
    name: "تحليل CBC",
    nameEn: "CBC Blood Test",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 45,
    priceInsurance: 65,
    doctors: 24,
    status: "active",
  },
  {
    id: 6,
    code: "SVC-102",
    name: "تحليل سكر صائم",
    nameEn: "Fasting Blood Sugar",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 25,
    priceInsurance: 40,
    doctors: 24,
    status: "active",
  },
  {
    id: 7,
    code: "SVC-103",
    name: "وظائف كلى",
    nameEn: "Kidney Function Tests",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 85,
    priceInsurance: 120,
    doctors: 24,
    status: "active",
  },
  {
    id: 8,
    code: "SVC-201",
    name: "أشعة صدر",
    nameEn: "Chest X-Ray",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 120,
    priceInsurance: 180,
    doctors: 8,
    status: "active",
  },
  {
    id: 9,
    code: "SVC-202",
    name: "أشعة رقبة",
    nameEn: "Neck X-Ray",
    specialty: "عظام",
    specialtyId: "more",
    priceCash: 145,
    priceInsurance: 210,
    doctors: 6,
    status: "active",
  },
  {
    id: 10,
    code: "SVC-301",
    name: "تنظيف أسنان",
    nameEn: "Dental Cleaning",
    specialty: "أسنان",
    specialtyId: "dental",
    priceCash: 250,
    priceInsurance: 320,
    doctors: 5,
    status: "active",
  },
  {
    id: 11,
    code: "SVC-302",
    name: "حشو أسنان",
    nameEn: "Dental Filling",
    specialty: "أسنان",
    specialtyId: "dental",
    priceCash: 350,
    priceInsurance: 480,
    doctors: 5,
    status: "active",
  },
  {
    id: 12,
    code: "SVC-401",
    name: "استشارة عن بُعد",
    nameEn: "Teleconsultation",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 80,
    priceInsurance: 100,
    doctors: 12,
    status: "active",
  },
  {
    id: 13,
    code: "SVC-501",
    name: "حقنة عضل",
    nameEn: "Intramuscular Injection",
    specialty: "عام",
    specialtyId: "more",
    priceCash: 30,
    priceInsurance: 45,
    doctors: 20,
    status: "inactive",
  },
];
