export const clinicStats = [
  {
    id: "specialties",
    label: "التخصصات",
    value: "8",
    note: "تخصص طبي متاح",
    icon: "clinic",
  },
  {
    id: "total",
    label: "إجمالي العيادات",
    value: "18",
    note: "في 3 فروع",
    icon: "service",
  },
  {
    id: "doctors",
    label: "أطباء نشطون",
    value: "24",
    note: "إجمالي الأطباء",
    icon: "doctor",
  },
  {
    id: "top",
    label: "أعلى تخصص",
    value: "باطنة",
    note: "185k ر.س هذا الشهر",
    icon: "chart",
    isText: true,
  },
];

export const specialties = [
  {
    id: 1,
    nameAr: "الباطنة",
    nameEn: "Internal Medicine",
    doctors: 6,
    visitsPerDay: 32,
    revenueMonth: "185k",
    branches: ["العليا", "النخيل", "الملقا"],
  },
  {
    id: 2,
    nameAr: "الجلدية",
    nameEn: "Dermatology",
    doctors: 4,
    visitsPerDay: 24,
    revenueMonth: "142k",
    branches: ["العليا", "النخيل"],
  },
  {
    id: 3,
    nameAr: "الأسنان",
    nameEn: "Dentistry",
    doctors: 5,
    visitsPerDay: 28,
    revenueMonth: "168k",
    branches: ["العليا", "النخيل", "الملقا"],
  },
  {
    id: 4,
    nameAr: "الأطفال",
    nameEn: "Pediatrics",
    doctors: 3,
    visitsPerDay: 20,
    revenueMonth: "98k",
    branches: ["العليا", "النخيل"],
  },
  {
    id: 5,
    nameAr: "النساء والولادة",
    nameEn: "OB-GYN",
    doctors: 3,
    visitsPerDay: 18,
    revenueMonth: "124k",
    branches: ["العليا", "الملقا"],
  },
  {
    id: 6,
    nameAr: "العظام",
    nameEn: "Orthopedics",
    doctors: 2,
    visitsPerDay: 12,
    revenueMonth: "88k",
    branches: ["العليا"],
  },
  {
    id: 7,
    nameAr: "العيون",
    nameEn: "Ophthalmology",
    doctors: 1,
    visitsPerDay: 8,
    revenueMonth: "64k",
    branches: ["النخيل"],
  },
  {
    id: 8,
    nameAr: "الأنف والأذن",
    nameEn: "ENT",
    doctors: 2,
    visitsPerDay: 14,
    revenueMonth: "76k",
    branches: ["العليا", "الملقا"],
  },
];
