export const branches = [
  {
    id: 1,
    name: 'فرع العليا',
    city: 'الرياض',
    address: 'شارع العليا العام، جوار برج المملكة',
    phone: '+966 11 XXX 4400',
    status: 'active',
    clinics: 7,
    doctors: 10,
    patients: 1420,
    revenue: '145k',
    toastLabel: 'عرض تفاصيل العليا',
  },
  {
    id: 2,
    name: 'فرع حي النخيل',
    city: 'الرياض',
    address: 'حي النخيل، شارع الأمير محمد بن سعد',
    phone: '+966 11 XXX 4500',
    status: 'active',
    clinics: 6,
    doctors: 8,
    patients: 1105,
    revenue: '118k',
    toastLabel: 'عرض تفاصيل حي النخيل',
  },
  {
    id: 3,
    name: 'فرع الملقا',
    city: 'الرياض',
    address: 'حي الملقا، شارع الأمير سلطان',
    phone: '+966 11 XXX 4600',
    status: 'active',
    clinics: 5,
    doctors: 6,
    patients: 716,
    revenue: '98k',
    toastLabel: 'عرض تفاصيل الملقا',
  },
]
