/**
 * Centralized route paths — use these instead of hardcoding strings
 */
export const ROUTES = {
  LOGIN:      '/login',
  DASHBOARD:  '/dashboard',
  QUEUE:      '/queue',
  CALENDAR:   '/calendar',
  PATIENTS:   '/patients',
  BRANCHES:   '/branches',
  CLINICS:    '/clinics',
  DOCTORS:    '/doctors',
  SERVICES:   '/services',
  STAFF:      '/staff',
  BILLING:    '/billing',
  INSURANCE:  '/insurance',
  REPORTS:    '/reports',
  ANALYTICS:  '/analytics',
  AUDIT:      '/audit',
  BRANDING:   '/branding',
  SETTINGS:   '/settings',
  ACCOUNT:    '/account',
  ROLES:      '/roles',
  CITIES:     '/cities',
  LOCATIONS:  '/locations',
  OFFERS:          '/offers',
  PROMO_CODES:     '/promo-codes',
  NOTIFICATIONS:   '/notifications',
  CLINIC_MANAGERS: '/clinic-managers',
  TIME_TABLES:     '/time-tables',
  PAGES:           '/pages',
}
