export const reportCards = [
  {
    id: 'revenue',
    title: 'تقرير الإيرادات',
    sub: 'يومي · أسبوعي · شهري',
    desc: 'إيرادات مفصّلة حسب الفرع والتخصص والطبيب وطريقة الدفع مع المقارنات',
    color: 'rgba(15,107,92,.1)',
    textColor: 'var(--brand)',
    icon: 'card',
    toast: 'تقرير الإيرادات',
  },
  {
    id: 'expenses',
    title: 'تقرير المصروفات',
    sub: 'رواتب · مشتريات · تشغيل',
    desc: 'تفصيل المصروفات حسب النوع والفرع مع الميزانية المعتمدة والانحراف',
    color: 'rgba(179,64,47,.1)',
    textColor: 'var(--danger)',
    icon: 'trend-down',
    toast: 'تقرير المصروفات',
  },
  {
    id: 'insurance',
    title: 'تقرير التأمين',
    sub: 'مطالبات · رفض · تحصيل',
    desc: 'متابعة المطالبات ونسب القبول والرفض حسب الشركة مع أسباب الرفض',
    color: 'rgba(44,109,170,.1)',
    textColor: 'var(--info)',
    icon: 'shield',
    toast: 'تقرير التأمين',
  },
  {
    id: 'visits',
    title: 'تقرير الزيارات',
    sub: 'زيارات · إلغاءات · عدم حضور',
    desc: 'إحصائيات الزيارات والإلغاءات حسب التخصص والطبيب والفرع',
    color: 'rgba(169,118,18,.1)',
    textColor: 'var(--warn)',
    icon: 'calendar',
    toast: 'تقرير الزيارات',
  },
  {
    id: 'doctors',
    title: 'تقرير أداء الأطباء',
    sub: 'إنتاجية · تقييم · مواعيد',
    desc: 'أداء كل طبيب: عدد الزيارات وتقييم المرضى والوقت ومعدل الإلغاء',
    color: 'rgba(15,107,92,.1)',
    textColor: 'var(--brand)',
    icon: 'bars',
    toast: 'تقرير الأداء',
  },
]
