export const actionFilters = [
  { id: "all", label: "كل العمليات" },
  { id: "add", label: "إضافة" },
  { id: "edit", label: "تعديل" },
  { id: "delete", label: "حذف" },
  { id: "export", label: "تصدير" },
];

// actionType maps to actionFilters ids
export const auditLogs = [
  {
    id: 1,
    time: "اليوم 11:22 ص",
    initial: "ن",
    user: "ناصر السالم",
    action: "تعديل إعدادات النظام",
    context: "الإعدادات العامة",
    actionType: "edit",
  },
  {
    id: 2,
    time: "اليوم 10:48 ص",
    initial: "ر",
    user: "رائد الحربي",
    action: "تسجيل حضور مريض جديد",
    context: "طابور · العليا",
    actionType: "add",
  },
  {
    id: 3,
    time: "اليوم 10:15 ص",
    initial: "ت",
    user: "تركي المالكي",
    action: "إضافة خدمة جديدة",
    context: "الخدمات",
    actionType: "add",
  },
  {
    id: 4,
    time: "اليوم 9:40 ص",
    initial: "ه",
    user: "هدى الشمري",
    action: "تعديل سعر كشف باطنة",
    context: "الخدمات والأسعار",
    actionType: "edit",
  },
  {
    id: 5,
    time: "أمس 4:30 م",
    initial: "م",
    user: "مها العنزي",
    action: "إضافة جدول لـ د. سارة",
    context: "الجداول · النخيل",
    actionType: "add",
  },
  {
    id: 6,
    time: "أمس 2:10 م",
    initial: "ن",
    user: "ناصر السالم",
    action: "تعطيل حساب جابر الدوسري",
    context: "المستخدمون",
    actionType: "edit",
  },
  {
    id: 7,
    time: "أمس 11:00 ص",
    initial: "ف",
    user: "فيصل الحارثي",
    action: "تصدير تقرير إيرادات يوليو",
    context: "التقارير المالية",
    actionType: "export",
  },
];
