export const queueStats = [
  {
    id: 'waiting',
    label: 'في الانتظار',
    value: '18',
    unit: '',
    note: 'مريضاً حالياً',
    icon: 'clock',
  },
  {
    id: 'in_exam',
    label: 'في الكشف',
    value: '4',
    unit: '',
    note: 'في العيادات الآن',
    icon: 'person',
  },
  {
    id: 'done',
    label: 'أنهوا اليوم',
    value: '62',
    unit: '',
    note: 'من 148 حجزاً',
    icon: 'check',
  },
  {
    id: 'avg_wait',
    label: 'متوسط الانتظار',
    value: '12',
    unit: 'د',
    note: 'حدّه المستهدف: 15 د',
    icon: 'timer',
  },
]

export const clinicFilters = [
  { id: 'all_clinics', label: 'جميع العيادات' },
  { id: 'internal',    label: 'باطنة (6)' },
  { id: 'skin',        label: 'جلدية (4)' },
  { id: 'dental',      label: 'أسنان (5)' },
  { id: 'pediatric',   label: 'أطفال (3)' },
]

export const branchFilters = [
  { id: 'all_branches', label: 'جميع الفروع' },
  { id: 'olaya',        label: 'العليا' },
  { id: 'nakheel',      label: 'النخيل' },
  { id: 'malqa',        label: 'الملقا' },
]

// status: 'in_exam' | 'waiting' | 'called' | 'done'
export const queueEntries = [
  {
    id: 1,
    initial: 'ن',
    name: 'نورة العتيبي',
    fileNo: 'ملف #30412',
    doctor: 'د. خالد العتيبي',
    clinic: 'internal',
    branch: 'olaya',
    arrivedAt: '10:15 ص',
    waitNote: null,
    status: 'in_exam',
  },
  {
    id: 2,
    initial: 'س',
    name: 'سعد المطيري',
    fileNo: 'ملف #29882',
    doctor: 'د. خالد العتيبي',
    clinic: 'internal',
    branch: 'olaya',
    arrivedAt: '10:22 ص',
    waitNote: 'وصل قبل 8 د',
    status: 'waiting',
  },
  {
    id: 3,
    initial: 'م',
    name: 'محمد الشمري',
    fileNo: 'ملف #30298',
    doctor: 'د. سارة الحربي',
    clinic: 'skin',
    branch: 'nakheel',
    arrivedAt: '10:30 ص',
    waitNote: 'وصل قبل 12 د',
    status: 'waiting',
  },
  {
    id: 4,
    initial: 'ف',
    name: 'فاطمة القرشي',
    fileNo: 'ملف #30115',
    doctor: 'د. عبدالله السالم',
    clinic: 'dental',
    branch: 'malqa',
    arrivedAt: '10:35 ص',
    waitNote: null,
    status: 'called',
  },
  {
    id: 5,
    initial: 'ه',
    name: 'هند الدوسري',
    fileNo: 'ملف #29710',
    doctor: 'د. رهف العنزي',
    clinic: 'pediatric',
    branch: 'olaya',
    arrivedAt: '10:40 ص',
    waitNote: null,
    status: 'in_exam',
  },
  {
    id: 6,
    initial: 'أ',
    name: 'أحمد الغامدي',
    fileNo: 'ملف #29655',
    doctor: 'د. سارة الحربي',
    clinic: 'skin',
    branch: 'nakheel',
    arrivedAt: '10:48 ص',
    waitNote: 'وصل قبل 15 د',
    status: 'waiting',
  },
  {
    id: 7,
    initial: 'خ',
    name: 'خالد الحربي',
    fileNo: 'ملف #29542',
    doctor: 'د. عبدالله السالم',
    clinic: 'dental',
    branch: 'olaya',
    arrivedAt: '10:55 ص',
    waitNote: 'وصل قبل 18 د',
    status: 'waiting',
  },
  {
    id: 8,
    initial: 'ل',
    name: 'لطيفة العتيبي',
    fileNo: 'ملف #29488',
    doctor: 'د. رهف العنزي',
    clinic: 'pediatric',
    branch: 'malqa',
    arrivedAt: '11:05 ص',
    waitNote: 'وصل قبل 5 د',
    status: 'waiting',
  },
  {
    id: 9,
    initial: 'ي',
    name: 'يوسف الشهري',
    fileNo: 'ملف #29455',
    doctor: 'د. خالد العتيبي',
    clinic: 'internal',
    branch: 'nakheel',
    arrivedAt: '11:10 ص',
    waitNote: 'وصل قبل 3 د',
    status: 'waiting',
  },
  {
    id: 10,
    initial: 'ر',
    name: 'ريم الرشيدي',
    fileNo: 'ملف #29401',
    doctor: 'د. سارة الحربي',
    clinic: 'skin',
    branch: 'malqa',
    arrivedAt: '9:30 ص',
    waitNote: null,
    status: 'done',
  },
  {
    id: 11,
    initial: 'ع',
    name: 'عبدالرحمن الفهد',
    fileNo: 'ملف #29387',
    doctor: 'د. عبدالله السالم',
    clinic: 'dental',
    branch: 'olaya',
    arrivedAt: '9:45 ص',
    waitNote: null,
    status: 'done',
  },
]
